import { LoanProduct } from '@/shared/types/loan';

export const loanProducts: LoanProduct[] = [
  // ── 은행 상품 18개 ──────────────────────────────────────────

  // KB국민은행
  {
    id: 'kb-001',
    category: 'bank',
    name: 'KB 전세자금대출',
    provider: 'KB국민은행',
    interestRate: 3.70,
    interestRateMin: 3.70,
    interestRateMax: 5.50,
    interestRateType: 'variable',
    maxAmount: 500000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity', 'equal-principal', 'equal-payment'],
    targetGroups: ['general'],
    description: '비대면 신청 가능, 전세보증금 80% 이내 최대 5억',
    conditions: ['무주택 세대주', '전세보증금의 80% 이내', '주택가격 9억 이하'],
    url: 'https://www.kbstar.com',
  },
  {
    id: 'kb-002',
    category: 'bank',
    name: 'KB 청년 전세자금대출',
    provider: 'KB국민은행',
    interestRate: 3.40,
    interestRateMin: 3.40,
    interestRateMax: 4.80,
    interestRateType: 'variable',
    maxAmount: 300000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity'],
    targetGroups: ['youth'],
    description: '청년 우대금리 적용, 최대 3억',
    conditions: ['만 19~34세', '무주택 세대주 또는 세대원', '연소득 5천만원 이하', '전세보증금 3억 이하'],
    url: 'https://www.kbstar.com',
  },

  // 신한은행
  {
    id: 'shinhan-001',
    category: 'bank',
    name: '신한 쏠편한 전세론',
    provider: '신한은행',
    interestRate: 3.60,
    interestRateMin: 3.60,
    interestRateMax: 5.40,
    interestRateType: 'variable',
    maxAmount: 500000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity', 'equal-principal', 'equal-payment'],
    targetGroups: ['general'],
    description: '신한 SOL 앱 비대면 신청, 0.3%p 우대금리',
    conditions: ['무주택 세대주', '전세계약서 및 확정일자 필수', '주택 시세 9억 이하'],
    url: 'https://www.shinhan.com',
  },
  {
    id: 'shinhan-002',
    category: 'bank',
    name: '신한 청년 전세론',
    provider: '신한은행',
    interestRate: 3.30,
    interestRateMin: 3.30,
    interestRateMax: 4.70,
    interestRateType: 'variable',
    maxAmount: 300000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity'],
    targetGroups: ['youth'],
    description: '청년 전용 우대금리 전세자금대출',
    conditions: ['만 19~34세', '무주택 세대주', '연소득 5천만원 이하'],
    url: 'https://www.shinhan.com',
  },

  // 우리은행
  {
    id: 'woori-001',
    category: 'bank',
    name: '우리 전세론',
    provider: '우리은행',
    interestRate: 3.65,
    interestRateMin: 3.65,
    interestRateMax: 5.45,
    interestRateType: 'variable',
    maxAmount: 500000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity', 'equal-principal', 'equal-payment'],
    targetGroups: ['general'],
    description: '우리WON뱅킹 비대면 신청 가능',
    conditions: ['무주택 세대주', '전세보증금 80% 이내', '주택가격 9억 이하'],
    url: 'https://www.wooribank.com',
  },
  {
    id: 'woori-002',
    category: 'bank',
    name: '우리 WON 전세론(청년)',
    provider: '우리은행',
    interestRate: 3.35,
    interestRateMin: 3.35,
    interestRateMax: 4.75,
    interestRateType: 'variable',
    maxAmount: 300000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity'],
    targetGroups: ['youth'],
    description: '청년 전용 WON 전세자금대출',
    conditions: ['만 19~34세', '무주택 세대주', '연소득 5천만원 이하'],
    url: 'https://www.wooribank.com',
  },

  // 하나은행
  {
    id: 'hana-001',
    category: 'bank',
    name: '하나 전세자금대출',
    provider: '하나은행',
    interestRate: 3.70,
    interestRateMin: 3.70,
    interestRateMax: 5.50,
    interestRateType: 'variable',
    maxAmount: 500000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity', 'equal-principal', 'equal-payment'],
    targetGroups: ['general'],
    description: '하나멤버스 우대금리 최대 0.5%p',
    conditions: ['무주택 세대주', '전세보증금 80% 이내', '주택가격 9억 이하'],
    url: 'https://www.hanabank.com',
  },
  {
    id: 'hana-002',
    category: 'bank',
    name: '하나 청년 전세자금대출',
    provider: '하나은행',
    interestRate: 3.30,
    interestRateMin: 3.30,
    interestRateMax: 4.70,
    interestRateType: 'variable',
    maxAmount: 300000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity'],
    targetGroups: ['youth'],
    description: '청년 전용 하나은행 전세자금대출',
    conditions: ['만 19~34세', '무주택', '연소득 5천만원 이하'],
    url: 'https://www.hanabank.com',
  },

  // NH농협은행
  {
    id: 'nh-001',
    category: 'bank',
    name: 'NH 전세자금대출',
    provider: 'NH농협은행',
    interestRate: 3.60,
    interestRateMin: 3.60,
    interestRateMax: 5.40,
    interestRateType: 'variable',
    maxAmount: 500000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity', 'equal-principal', 'equal-payment'],
    targetGroups: ['general'],
    description: 'NH농협은행 일반 전세자금대출',
    conditions: ['무주택 세대주', '전세보증금 80% 이내', '주택가격 9억 이하'],
    url: 'https://www.nonghyup.com',
  },
  {
    id: 'nh-002',
    category: 'bank',
    name: 'NH 청년 전세자금대출',
    provider: 'NH농협은행',
    interestRate: 3.30,
    interestRateMin: 3.30,
    interestRateMax: 4.70,
    interestRateType: 'variable',
    maxAmount: 300000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity'],
    targetGroups: ['youth'],
    description: 'NH농협 청년 우대 전세자금대출',
    conditions: ['만 19~34세', '무주택', '연소득 5천만원 이하'],
    url: 'https://www.nonghyup.com',
  },

  // IBK기업은행
  {
    id: 'ibk-001',
    category: 'bank',
    name: 'IBK 전세자금대출',
    provider: 'IBK기업은행',
    interestRate: 3.65,
    interestRateMin: 3.65,
    interestRateMax: 5.45,
    interestRateType: 'variable',
    maxAmount: 500000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity', 'equal-principal', 'equal-payment'],
    targetGroups: ['general'],
    description: '중소기업 재직자 우대금리 적용',
    conditions: ['무주택 세대주', '중소기업 재직자 우대', '전세보증금 80% 이내'],
    url: 'https://www.ibk.co.kr',
  },

  // SC제일은행
  {
    id: 'sc-001',
    category: 'bank',
    name: 'SC제일 전세자금대출',
    provider: 'SC제일은행',
    interestRate: 3.80,
    interestRateMin: 3.80,
    interestRateMax: 5.60,
    interestRateType: 'variable',
    maxAmount: 500000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity', 'equal-principal', 'equal-payment'],
    targetGroups: ['general'],
    description: 'SC제일은행 일반 전세자금대출',
    conditions: ['무주택 세대주', '전세보증금 80% 이내'],
    url: 'https://www.standardchartered.co.kr',
  },

  // 카카오뱅크
  {
    id: 'kakao-001',
    category: 'bank',
    name: '카카오뱅크 전세자금대출',
    provider: '카카오뱅크',
    interestRate: 3.45,
    interestRateMin: 3.45,
    interestRateMax: 5.10,
    interestRateType: 'variable',
    maxAmount: 500000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity'],
    targetGroups: ['general'],
    description: '100% 비대면, 카카오앱으로 간편 신청',
    conditions: ['무주택 세대주', '전세보증금 80% 이내', '주택가격 9억 이하'],
    url: 'https://www.kakaobank.com',
  },
  {
    id: 'kakao-002',
    category: 'bank',
    name: '카카오뱅크 청년 전세자금대출',
    provider: '카카오뱅크',
    interestRate: 3.20,
    interestRateMin: 3.20,
    interestRateMax: 4.60,
    interestRateType: 'variable',
    maxAmount: 300000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity'],
    targetGroups: ['youth'],
    description: '청년 전용, 100% 비대면 카카오앱 신청',
    conditions: ['만 19~34세', '무주택', '연소득 5천만원 이하'],
    url: 'https://www.kakaobank.com',
  },

  // 케이뱅크
  {
    id: 'kbank-001',
    category: 'bank',
    name: '케이뱅크 전세자금대출',
    provider: '케이뱅크',
    interestRate: 3.50,
    interestRateMin: 3.50,
    interestRateMax: 5.20,
    interestRateType: 'variable',
    maxAmount: 500000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity'],
    targetGroups: ['general'],
    description: '케이뱅크 비대면 전세자금대출',
    conditions: ['무주택 세대주', '전세보증금 80% 이내'],
    url: 'https://www.kbanknow.com',
  },

  // 토스뱅크
  {
    id: 'toss-001',
    category: 'bank',
    name: '토스뱅크 전세자금대출',
    provider: '토스뱅크',
    interestRate: 3.50,
    interestRateMin: 3.50,
    interestRateMax: 5.20,
    interestRateType: 'variable',
    maxAmount: 300000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity'],
    targetGroups: ['general', 'youth'],
    description: '토스앱 100% 비대면, 한도 최대 3억',
    conditions: ['무주택 세대주', '전세보증금 80% 이내'],
    url: 'https://www.tossbank.com',
  },

  // BNK부산은행
  {
    id: 'bnk-001',
    category: 'bank',
    name: 'BNK 전세자금대출',
    provider: 'BNK부산은행',
    interestRate: 3.70,
    interestRateMin: 3.70,
    interestRateMax: 5.50,
    interestRateType: 'variable',
    maxAmount: 500000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity', 'equal-principal', 'equal-payment'],
    targetGroups: ['general'],
    description: '부산·경남 지역 우대 혜택',
    conditions: ['무주택 세대주', '전세보증금 80% 이내'],
    url: 'https://www.busanbank.co.kr',
  },

  // DGB대구은행
  {
    id: 'dgb-001',
    category: 'bank',
    name: 'DGB 전세자금대출',
    provider: 'DGB대구은행',
    interestRate: 3.70,
    interestRateMin: 3.70,
    interestRateMax: 5.50,
    interestRateType: 'variable',
    maxAmount: 500000000,
    minPeriod: 12,
    maxPeriod: 24,
    repaymentMethods: ['maturity', 'equal-principal', 'equal-payment'],
    targetGroups: ['general'],
    description: '대구·경북 지역 우대 혜택',
    conditions: ['무주택 세대주', '전세보증금 80% 이내'],
    url: 'https://www.dgb.co.kr',
  },

  // ── 정부기금 상품 6개 ────────────────────────────────────────

  {
    id: 'gov-001',
    category: 'government',
    name: '버팀목전세자금 (일반)',
    provider: '주택도시기금',
    interestRate: 2.30,
    interestRateMin: 2.30,
    interestRateMax: 2.90,
    interestRateType: 'fixed',
    maxAmount: 120000000,
    minPeriod: 24,
    maxPeriod: 48,
    repaymentMethods: ['maturity'],
    targetGroups: ['general'],
    description: '무주택 서민 주거안정을 위한 저금리 정책 전세자금',
    conditions: [
      '무주택 세대주',
      '연소득 5천만원 이하 (부부합산)',
      '순자산 3.45억 이하',
      '전용면적 85㎡ 이하',
      '수도권 전세금 3억 이하',
    ],
    url: 'https://nhuf.molit.go.kr',
  },
  {
    id: 'gov-002',
    category: 'government',
    name: '청년전용 버팀목전세자금',
    provider: '주택도시기금',
    interestRate: 1.80,
    interestRateMin: 1.80,
    interestRateMax: 2.70,
    interestRateType: 'fixed',
    maxAmount: 200000000,
    minPeriod: 24,
    maxPeriod: 48,
    repaymentMethods: ['maturity'],
    targetGroups: ['youth'],
    description: '청년 우대금리 최저 1.8%, 수도권 최대 2억',
    conditions: [
      '만 19~34세 무주택 단독세대주',
      '연소득 5천만원 이하',
      '순자산 3.45억 이하',
      '전용면적 85㎡ 이하',
    ],
    url: 'https://nhuf.molit.go.kr',
  },
  {
    id: 'gov-003',
    category: 'government',
    name: '신혼부부전용 전세자금',
    provider: '주택도시기금',
    interestRate: 1.20,
    interestRateMin: 1.20,
    interestRateMax: 2.70,
    interestRateType: 'fixed',
    maxAmount: 300000000,
    minPeriod: 24,
    maxPeriod: 48,
    repaymentMethods: ['maturity'],
    targetGroups: ['newlywed'],
    description: '신혼부부 소득에 따라 1.2~2.7%, 최대 3억',
    conditions: [
      '혼인 7년 이내 또는 3개월 내 결혼 예정',
      '무주택 세대주',
      '연소득 7천5백만원 이하 (부부합산)',
      '순자산 3.45억 이하',
    ],
    url: 'https://nhuf.molit.go.kr',
  },
  {
    id: 'gov-004',
    category: 'government',
    name: '다자녀가구 전세자금',
    provider: '주택도시기금',
    interestRate: 1.00,
    interestRateMin: 1.00,
    interestRateMax: 2.70,
    interestRateType: 'fixed',
    maxAmount: 300000000,
    minPeriod: 24,
    maxPeriod: 48,
    repaymentMethods: ['maturity'],
    targetGroups: ['multi-child'],
    description: '자녀 수에 따라 최저 1.0%, 2자녀 이상 가구',
    conditions: [
      '2자녀 이상 가구',
      '무주택 세대주',
      '연소득 6천만원 이하 (부부합산)',
      '순자산 3.45억 이하',
    ],
    url: 'https://nhuf.molit.go.kr',
  },
  {
    id: 'gov-005',
    category: 'government',
    name: '주거안정월세대출 (청년)',
    provider: '주택도시기금',
    interestRate: 1.50,
    interestRateMin: 1.50,
    interestRateMax: 2.50,
    interestRateType: 'fixed',
    maxAmount: 9600000,
    minPeriod: 24,
    maxPeriod: 24,
    repaymentMethods: ['equal-payment'],
    targetGroups: ['youth'],
    description: '월 최대 40만원×24개월, 취업준비생·사회초년생 대상',
    conditions: ['만 19~34세', '무주택 단독세대주', '연소득 2천만원 이하', '월세 60만원 이하'],
    url: 'https://nhuf.molit.go.kr',
  },
  {
    id: 'gov-006',
    category: 'government',
    name: '주거안정월세대출 (일반)',
    provider: '주택도시기금',
    interestRate: 2.00,
    interestRateMin: 2.00,
    interestRateMax: 3.00,
    interestRateType: 'fixed',
    maxAmount: 9600000,
    minPeriod: 24,
    maxPeriod: 24,
    repaymentMethods: ['equal-payment'],
    targetGroups: ['general'],
    description: '무주택 세대주 월세 지원, 월 최대 40만원',
    conditions: ['무주택 세대주', '연소득 5천만원 이하', '순자산 3.45억 이하', '월세 60만원 이하'],
    url: 'https://nhuf.molit.go.kr',
  },

  // ── 공공임대 상품 6개 ────────────────────────────────────────

  {
    id: 'lh-001',
    category: 'public',
    name: 'LH 청년 전세임대',
    provider: 'LH한국토지주택공사',
    interestRate: 1.00,
    interestRateMin: 1.00,
    interestRateMax: 2.00,
    interestRateType: 'fixed',
    maxAmount: 120000000,
    minPeriod: 24,
    maxPeriod: 72,
    repaymentMethods: ['maturity'],
    targetGroups: ['youth'],
    description: 'LH가 전세계약 후 청년에 재임대, 수도권 최대 1.2억',
    conditions: ['만 19~39세 무주택 청년', '대학생·취업준비생·사회초년생', '연소득 5천만원 이하'],
    url: 'https://www.lh.or.kr',
  },
  {
    id: 'lh-002',
    category: 'public',
    name: 'LH 신혼부부 전세임대 I',
    provider: 'LH한국토지주택공사',
    interestRate: 1.00,
    interestRateMin: 1.00,
    interestRateMax: 2.00,
    interestRateType: 'fixed',
    maxAmount: 240000000,
    minPeriod: 24,
    maxPeriod: 72,
    repaymentMethods: ['maturity'],
    targetGroups: ['newlywed'],
    description: '저소득 신혼부부 우선 지원, 최대 2.4억',
    conditions: [
      '혼인 7년 이내 또는 예비신혼부부',
      '무주택 세대구성원',
      '도시근로자 월평균소득 70% 이하',
    ],
    url: 'https://www.lh.or.kr',
  },
  {
    id: 'lh-003',
    category: 'public',
    name: 'LH 신혼부부 전세임대 II',
    provider: 'LH한국토지주택공사',
    interestRate: 1.00,
    interestRateMin: 1.00,
    interestRateMax: 2.00,
    interestRateType: 'fixed',
    maxAmount: 240000000,
    minPeriod: 24,
    maxPeriod: 72,
    repaymentMethods: ['maturity'],
    targetGroups: ['newlywed'],
    description: '소득 기준 완화 신혼부부 II유형, 최대 2.4억',
    conditions: [
      '혼인 7년 이내 또는 예비신혼부부',
      '무주택 세대구성원',
      '도시근로자 월평균소득 100% 이하',
    ],
    url: 'https://www.lh.or.kr',
  },
  {
    id: 'lh-004',
    category: 'public',
    name: 'LH 고령자 전세임대',
    provider: 'LH한국토지주택공사',
    interestRate: 1.00,
    interestRateMin: 1.00,
    interestRateMax: 2.00,
    interestRateType: 'fixed',
    maxAmount: 100000000,
    minPeriod: 24,
    maxPeriod: 72,
    repaymentMethods: ['maturity'],
    targetGroups: ['senior'],
    description: '만 65세 이상 주거약자 우선 지원',
    conditions: ['만 65세 이상', '무주택 세대구성원', '도시근로자 월평균소득 50% 이하'],
    url: 'https://www.lh.or.kr',
  },
  {
    id: 'sh-001',
    category: 'public',
    name: 'SH 청년 전세임대',
    provider: 'SH서울주택도시공사',
    interestRate: 1.00,
    interestRateMin: 1.00,
    interestRateMax: 2.00,
    interestRateType: 'fixed',
    maxAmount: 150000000,
    minPeriod: 24,
    maxPeriod: 72,
    repaymentMethods: ['maturity'],
    targetGroups: ['youth'],
    description: '서울 청년 전세임대, 서울 시세 반영 최대 1.5억',
    conditions: [
      '서울 거주 또는 서울 소재 대학 재학·취업 청년',
      '만 19~39세 무주택',
      '연소득 5천만원 이하',
    ],
    url: 'https://www.i-sh.co.kr',
  },
  {
    id: 'sh-002',
    category: 'public',
    name: 'SH 신혼부부 전세임대',
    provider: 'SH서울주택도시공사',
    interestRate: 1.00,
    interestRateMin: 1.00,
    interestRateMax: 2.00,
    interestRateType: 'fixed',
    maxAmount: 270000000,
    minPeriod: 24,
    maxPeriod: 72,
    repaymentMethods: ['maturity'],
    targetGroups: ['newlywed'],
    description: '서울 신혼부부 전세임대, 최대 2.7억',
    conditions: [
      '서울 거주 신혼부부 (혼인 7년 이내)',
      '무주택 세대구성원',
      '도시근로자 월평균소득 100% 이하',
    ],
    url: 'https://www.i-sh.co.kr',
  },
];
